image: debian:buster

stages:
  - build
  - release

build:matterbridge:arm64:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context=. --dockerfile=matterbridge-arm64/Dockerfile --no-push

release:matterbridge:arm64:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
    - /kaniko/executor --context=. --dockerfile=matterbridge-arm64/Dockerfile --destination="nerzhul/matterbridge-arm64:1.18.3"
  only:
    - master
